'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer, Header, Sole } from '@irachus/ui';
import { LOCALISATION, BANNER, MENU_LIST,  socialNetowrk, internalLinkList } from '../common/constant';
import '../common/i18n';
import { useTranslation } from 'react-i18next';
import {  pageContainsInit} from '@irachus/jscommon';
import useMenuList from '../hooks/useMenuList';
import useFooterContain from '../hooks/useFooterContains';
import useEnhancedLink from '../hooks/useEnhancedLink';
import { useEffect, useState } from 'react';
import useLocalisation from '../hooks/useLocalisation';
const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Irisations',
//   description: 'Generated by Irachus'
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {t, i18n } = useTranslation();

  const changeLang = (lng: string) => {
    if (i18n.changeLanguage) {
      i18n.changeLanguage(lng);
    } else {
      console.error('i18n.changeLanguage is not a function');
    }
  };

  const { pageContains: footerContains } = useFooterContain();
  const { menuList } = useMenuList(MENU_LIST);
  const { localeEnhancedLink : localInternalLinkList } = useEnhancedLink(internalLinkList);
  const { localeEnhancedLink : localSocialNetowrk } = useEnhancedLink(socialNetowrk);
  const { localisation } = useLocalisation(LOCALISATION)

  return (
    <html lang='en'>
      <head>
        <title>Irisations</title>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'></meta>
      </head>
      <body className={inter.className + ' max-w-screen-xl  mx-auto '}>
        <div className='w-full   bg-primary-100 '>
          <Header
            banner={BANNER}
            homeUrl='/'
            localisation={localisation}
            menuList={menuList || []}
            changeLang={changeLang}
          />
          <div className='z-bodyLayout flex-grow  w-full  mx-auto pt-6 '>
            {children}
          </div>
          <Footer pageContains={footerContains || pageContainsInit}  
         />
          <Sole
            internalLinkList ={localInternalLinkList}
            socialNetwork={localSocialNetowrk}
            yearStart={2014}
            brand={BANNER}                    
          />
        </div>
      </body>
    </html>
  );
}
